-- Run this once in your Supabase project's SQL Editor (Dashboard → SQL Editor → New query).
-- Safe to re-run: every statement is idempotent (IF NOT EXISTS / OR REPLACE).

-- ============================================================================
-- consultation_requests — Contact form submissions (Phase 2, section 4.4)
-- ============================================================================
create table if not exists consultation_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  practice_area text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'read', 'replied')),
  created_at timestamptz not null default now()
);

alter table consultation_requests enable row level security;

drop policy if exists "Public can submit consultation requests" on consultation_requests;
create policy "Public can submit consultation requests"
  on consultation_requests for insert
  to anon
  with check (true);

drop policy if exists "Authenticated users can view consultation requests" on consultation_requests;
create policy "Authenticated users can view consultation requests"
  on consultation_requests for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can update consultation requests" on consultation_requests;
create policy "Authenticated users can update consultation requests"
  on consultation_requests for update
  to authenticated
  using (true);

-- ============================================================================
-- blog_posts — CMS-managed articles (Phase 2, section 4.1)
-- ============================================================================
create table if not exists blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null,
  excerpt text not null,
  content text not null,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table blog_posts enable row level security;

drop policy if exists "Public can view published posts" on blog_posts;
create policy "Public can view published posts"
  on blog_posts for select
  to anon
  using (published = true);

drop policy if exists "Authenticated users can view all posts" on blog_posts;
create policy "Authenticated users can view all posts"
  on blog_posts for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can insert posts" on blog_posts;
create policy "Authenticated users can insert posts"
  on blog_posts for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update posts" on blog_posts;
create policy "Authenticated users can update posts"
  on blog_posts for update
  to authenticated
  using (true);

drop policy if exists "Authenticated users can delete posts" on blog_posts;
create policy "Authenticated users can delete posts"
  on blog_posts for delete
  to authenticated
  using (true);

-- Keep updated_at current on every edit.
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists blog_posts_set_updated_at on blog_posts;
create trigger blog_posts_set_updated_at
  before update on blog_posts
  for each row
  execute function set_updated_at();

-- ============================================================================
-- ⚠️ IMPORTANT — these RLS policies grant full access to ANY authenticated
-- Supabase user, because right now the only accounts are the site admin(s).
-- If you later add real client accounts (Phase 2 client portal), add a
-- `role` column (e.g. on a `profiles` table keyed to auth.users) and rewrite
-- the `to authenticated` policies above to check `role = 'admin'` instead —
-- otherwise every client login would also get admin access to this data.
-- ============================================================================
