import type { Metadata } from 'next';
import Link from '@/components/NoPrefetchLink';
import PageHero from '@/components/PageHero';
import { getFirm } from '@/lib/content/firm';

export const metadata: Metadata = { title: 'حریم خصوصی', description: 'نحوه دریافت، استفاده و نگهداری اطلاعات کاربران و موکلان در وب‌سایت دفتر وکالت.', alternates: { canonical: '/privacy' } };

export default async function PrivacyPage() {
  const firm = await getFirm();
  return <><PageHero eyebrow="شفافیت و محرمانگی" title="حریم خصوصی" description="توضیح روشن درباره اطلاعاتی که هنگام استفاده از خدمات آنلاین ثبت می‌شود و نحوه استفاده و نگهداری آن." /><section className="editorial-section"><div className="mx-auto max-w-4xl px-4 sm:px-6"><div className="mb-7 flex flex-col gap-2 rounded-xl sm:flex-row sm:items-center sm:justify-between border border-border bg-card px-5 py-4"><span className="text-sm font-extrabold text-foreground">سیاست حریم خصوصی دفتر</span><span className="text-xs font-bold text-muted-foreground">آخرین به‌روزرسانی: مرداد ۱۴۰۵</span></div><div className="legal-card p-6 md:p-10"><div className="prose-legal space-y-8"><section><h2>چه اطلاعاتی دریافت می‌شود؟</h2><p>اطلاعاتی که خودتان در فرم‌های مشاوره، حساب کاربری، پرونده، نوبت یا مکاتبات وارد می‌کنید؛ مانند نام، شماره تماس، ایمیل، شرح موضوع، اسناد ارسالی و اطلاعات مرتبط با پرونده.</p></section><section><h2>هدف استفاده از اطلاعات</h2><p>اطلاعات برای پاسخ‌گویی به درخواست مشاوره، مدیریت ارتباط با موکل، ارائه خدمات حقوقی، مدیریت نوبت و پرونده، حفظ امنیت حساب و انجام الزامات اداری مرتبط استفاده می‌شود.</p></section><section><h2>محرمانگی و دسترسی</h2><p>دسترسی به اطلاعات پرونده و مکاتبات به کاربران مجاز محدود می‌شود. با این حال، ارسال اطلاعات در اینترنت همیشه بدون ریسک نیست؛ اطلاعات بسیار حساس را فقط از مسیرهای مورد تأیید دفتر ارسال کنید.</p></section><section><h2>نگهداری و حذف</h2><p>اطلاعات تا زمانی که برای ارائه خدمت، پیگیری پرونده، امنیت یا تکالیف قانونی و حرفه‌ای لازم باشد نگهداری می‌شود. درخواست‌های مربوط به اصلاح یا حذف اطلاعات، در حدود الزامات قانونی و حرفه‌ای، از طریق اطلاعات تماس دفتر قابل پیگیری است.</p></section><section><h2>سرویس‌های فنی</h2><p>وب‌سایت ممکن است برای میزبانی، پایگاه داده و نگهداری فایل‌ها از ارائه‌دهندگان زیرساخت استفاده کند. در صورت فعال‌شدن ابزارهای تحلیلی یا سرویس‌های غیرضروری جدید، این صفحه باید متناسب با آن به‌روزرسانی شود.</p></section><section><h2>تماس درباره حریم خصوصی</h2><p>برای پیگیری موضوعات مرتبط با اطلاعات شخصی می‌توانید از طریق <Link href={`mailto:${firm.email}`} className="font-bold text-primary underline underline-offset-4">{firm.email}</Link> یا شماره <Link href={firm.phoneHref} className="font-bold text-primary underline underline-offset-4">{firm.phone}</Link> با دفتر تماس بگیرید.</p></section></div></div></div></section></>;
}
