import type { Metadata } from 'next';
import Link from '@/components/NoPrefetchLink';
import PageHero from '@/components/PageHero';
import { getFirm } from '@/lib/content/firm';

export const metadata: Metadata = { title: 'شرایط استفاده', description: 'شرایط استفاده از وب‌سایت، محتوای حقوقی و خدمات آنلاین دفتر وکالت.', alternates: { canonical: '/terms' } };

export default async function TermsPage() {
  const firm = await getFirm();
  return <><PageHero eyebrow="چارچوب استفاده" title="شرایط استفاده" description="حدود استفاده از محتوای حقوقی، فرم‌ها، حساب کاربری، رزرو نوبت و خدمات آنلاین این وب‌سایت." /><section className="editorial-section"><div className="mx-auto max-w-4xl px-4 sm:px-6"><div className="mb-7 flex flex-col gap-2 rounded-xl sm:flex-row sm:items-center sm:justify-between border border-border bg-card px-5 py-4"><span className="text-sm font-extrabold text-foreground">شرایط استفاده از وب‌سایت</span><span className="text-xs font-bold text-muted-foreground">آخرین به‌روزرسانی: مرداد ۱۴۰۵</span></div><div className="legal-card p-6 md:p-10"><div className="prose-legal space-y-8"><section><h2>ماهیت محتوای سایت</h2><p>مطالب عمومی سایت برای اطلاع‌رسانی و آموزش حقوقی تهیه می‌شوند و به‌تنهایی جایگزین بررسی اسناد و مشاوره حقوقی متناسب با شرایط یک پرونده نیستند.</p></section><section><h2>تشکیل رابطه وکیل و موکل</h2><p>ارسال فرم، ثبت‌نام، رزرو نوبت یا ارسال پیام به‌تنهایی به معنای قبول وکالت یا ایجاد رابطه وکیل و موکل نیست. پذیرش پرونده و حدود خدمات پس از بررسی و توافق مشخص می‌شود.</p></section><section><h2>دقت اطلاعات</h2><p>تلاش می‌شود محتوای حقوقی با منابع معتبر و تاریخ به‌روزرسانی روشن منتشر شود، اما قوانین، رویه‌ها و شرایط پرونده‌ها ممکن است تغییر کنند. برای تصمیم حقوقی مهم باید وضعیت روز و اسناد همان پرونده بررسی شود.</p></section><section><h2>حساب کاربری و اسناد</h2><p>کاربر مسئول حفظ دسترسی حساب خود و صحت اطلاعاتی است که ارسال می‌کند. از بارگذاری فایل‌های نامرتبط، مخرب یا اطلاعات اشخاص ثالث بدون مجوز قانونی خودداری شود.</p></section><section><h2>رزرو و هزینه خدمات</h2><p>ثبت زمان پیشنهادی نوبت، تأیید نهایی نوبت محسوب نمی‌شود مگر این‌که دفتر آن را تأیید کند. هزینه و دامنه هر خدمت بر اساس نوع درخواست و توافق نهایی تعیین می‌شود.</p></section><section><h2>ارتباط</h2><p>برای پرسش درباره شرایط استفاده می‌توانید از صفحه <Link href="/contact" className="font-bold text-primary underline underline-offset-4">تماس با ما</Link> یا شماره <Link href={firm.phoneHref} className="font-bold text-primary underline underline-offset-4">{firm.phone}</Link> استفاده کنید.</p></section></div></div></div></section></>;
}
