import { Skeleton } from '@/components/ui/skeleton';
import { BackLinkSkeleton, DashboardHeaderSkeleton, FilterBarSkeleton, FormFieldSkeleton, ListRowSkeleton, TextareaFieldSkeleton } from './SkeletonBlocks';

export function AdminDashboardSkeleton(){return <div role="status" aria-label="در حال بارگذاری داشبورد مدیریت"><DashboardHeaderSkeleton action/><div className="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="dashboard-stat"><div className="flex items-start justify-between"><div className="space-y-3"><Skeleton className="h-4 w-28"/><Skeleton tone="accent" className="h-9 w-16"/></div><Skeleton tone="accent" className="size-11 rounded-lg"/></div></div>)}</div><div className="grid grid-cols-1 gap-6 xl:grid-cols-2">{['requests','cases'].map((key)=><section key={key} className="dashboard-card p-5"><div className="mb-5 flex items-center justify-between"><Skeleton className="h-5 w-40"/><Skeleton tone="accent" className="h-4 w-20"/></div><div className="space-y-3">{Array.from({length:5}).map((_,i)=><ListRowSkeleton key={i}/>)}</div></section>)}</div></div>}

export function AdminMessagesSkeleton(){return <div role="status" aria-label="در حال بارگذاری درخواست‌های مشاوره"><DashboardHeaderSkeleton/><FilterBarSkeleton/><div className="space-y-4">{Array.from({length:6}).map((_,i)=><article key={i} className="dashboard-card p-5"><div className="flex items-start justify-between"><div className="flex-1 space-y-3"><Skeleton className="h-5 w-40"/><Skeleton className="h-3 w-52"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-4/5"/></div><Skeleton tone="accent" className="h-6 w-20 rounded-full"/></div><div className="mt-5 flex gap-2"><Skeleton className="h-9 w-24"/><Skeleton className="h-9 w-20"/></div></article>)}</div></div>}

export function AdminBlogSkeleton(){return <div role="status" aria-label="در حال بارگذاری مدیریت وبلاگ"><DashboardHeaderSkeleton action/><div className="grid grid-cols-1 gap-4 lg:grid-cols-2">{Array.from({length:6}).map((_,i)=><article key={i} className="dashboard-card flex overflow-hidden flex-col sm:flex-row"><Skeleton tone="accent" className="aspect-video w-full rounded-none sm:w-44 sm:shrink-0"/><div className="flex-1 p-5"><div className="mb-3 flex justify-between"><Skeleton tone="accent" className="h-6 w-20 rounded-full"/><Skeleton className="h-3 w-16"/></div><Skeleton className="mb-3 h-5 w-4/5"/><Skeleton className="mb-2 h-3 w-32"/><Skeleton className="h-3 w-24"/><div className="mt-5 flex gap-2"><Skeleton className="h-9 w-20"/><Skeleton className="h-9 w-20"/><Skeleton className="h-9 w-16"/></div></div></article>)}</div></div>}

export function AdminBlogEditorSkeleton(){return <div role="status" aria-label="در حال بارگذاری ویرایشگر وبلاگ" className="mx-auto max-w-4xl"><BackLinkSkeleton/><DashboardHeaderSkeleton/><section className="dashboard-card grid grid-cols-1 gap-5 p-6 md:grid-cols-2"><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><TextareaFieldSkeleton rows={6}/><div className="col-span-full space-y-3"><Skeleton className="h-4 w-28"/><Skeleton tone="accent" className="aspect-[2/1] w-full rounded-lg"/></div><div className="col-span-full flex justify-end gap-3"><Skeleton className="h-10 w-28"/><Skeleton tone="accent" className="h-10 w-32"/></div></section></div>}

export function AdminClientsSkeleton(){return <div role="status" aria-label="در حال بارگذاری موکلین"><DashboardHeaderSkeleton/><div className="dashboard-card mb-5 flex flex-col gap-3 p-4 sm:flex-row"><Skeleton className="h-11 flex-1"/><Skeleton tone="accent" className="h-11 w-24"/></div><div className="hidden overflow-hidden rounded-lg border border-border md:block"><div className="grid grid-cols-5 gap-4 bg-muted/40 p-4">{Array.from({length:5}).map((_,i)=><Skeleton key={i} className="h-3 w-20"/>)}</div>{Array.from({length:7}).map((_,r)=><div key={r} className="grid grid-cols-5 gap-4 border-t border-border p-4">{Array.from({length:5}).map((_,c)=><Skeleton key={c} className="h-4 w-4/5"/>)}</div>)}</div><div className="grid gap-3 md:hidden">{Array.from({length:5}).map((_,i)=><ListRowSkeleton key={i}/>)}</div></div>}

export function AdminClientDetailSkeleton(){return <div role="status" aria-label="در حال بارگذاری اطلاعات موکل"><BackLinkSkeleton/><DashboardHeaderSkeleton action/><section className="dashboard-card mb-6 grid grid-cols-1 gap-4 p-5 md:grid-cols-2 xl:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i} className="space-y-2"><Skeleton className="h-3 w-20"/><Skeleton className="h-5 w-36"/></div>)}</section><div className="grid grid-cols-1 gap-6 xl:grid-cols-2">{Array.from({length:2}).map((_,i)=><section key={i} className="dashboard-card p-5"><div className="mb-5 flex justify-between"><Skeleton className="h-5 w-32"/><Skeleton tone="accent" className="size-5"/></div><div className="space-y-3">{Array.from({length:4}).map((_,r)=><ListRowSkeleton key={r}/>)}</div></section>)}</div><section className="dashboard-card mt-6 p-5"><Skeleton className="mb-5 h-5 w-40"/><div className="space-y-3">{Array.from({length:4}).map((_,i)=><ListRowSkeleton key={i}/>)}</div></section></div>}

export function AdminCasesSkeleton(){return <div role="status" aria-label="در حال بارگذاری پرونده‌ها"><DashboardHeaderSkeleton action/><FilterBarSkeleton/><div className="hidden overflow-hidden rounded-lg border border-border md:block"><div className="grid grid-cols-6 gap-4 bg-muted/40 p-4">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-3 w-20"/>)}</div>{Array.from({length:7}).map((_,r)=><div key={r} className="grid grid-cols-6 gap-4 border-t border-border p-4">{Array.from({length:6}).map((_,c)=><Skeleton key={c} className="h-4 w-4/5"/>)}</div>)}</div><div className="grid gap-3 md:hidden">{Array.from({length:5}).map((_,i)=><ListRowSkeleton key={i}/>)}</div></div>}

export function AdminCaseNewSkeleton(){return <div role="status" aria-label="در حال بارگذاری فرم پرونده جدید" className="mx-auto max-w-4xl"><BackLinkSkeleton/><DashboardHeaderSkeleton/><section className="dashboard-card grid grid-cols-1 gap-5 p-6 md:grid-cols-2"><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><TextareaFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><div className="col-span-full flex justify-end"><Skeleton tone="accent" className="h-11 w-32"/></div></section></div>}

export function AdminCaseDetailSkeleton(){return <div role="status" aria-label="در حال بارگذاری جزئیات پرونده"><BackLinkSkeleton/><DashboardHeaderSkeleton action/><div className="grid grid-cols-1 items-start gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-6"><section className="dashboard-card grid grid-cols-1 gap-5 p-6 md:grid-cols-2"><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><TextareaFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><Skeleton tone="accent" className="h-11 w-36"/></section><section className="dashboard-card p-5"><div className="mb-5 flex justify-between"><Skeleton className="h-5 w-44"/><Skeleton className="h-3 w-16"/></div><div className="space-y-5">{Array.from({length:4}).map((_,i)=><div key={i} className="border-r-2 border-accent/30 pr-5"><Skeleton className="mb-2 h-4 w-40"/><Skeleton className="mb-3 h-3 w-28"/><Skeleton className="h-3 w-full"/></div>)}</div></section><section className="dashboard-card p-5"><Skeleton className="mb-5 h-5 w-32"/>{Array.from({length:3}).map((_,i)=><div key={i} className="mb-3 flex items-center justify-between rounded-lg border border-border p-4"><div className="flex items-center gap-3"><Skeleton tone="accent" className="size-10"/><div><Skeleton className="mb-2 h-4 w-36"/><Skeleton className="h-3 w-28"/></div></div><Skeleton className="h-9 w-20"/></div>)}</section></div><div className="space-y-6 xl:sticky xl:top-24"><section className="dashboard-card p-5"><Skeleton className="mb-5 h-5 w-36"/><FormFieldSkeleton/><div className="mt-4"><TextareaFieldSkeleton/></div><Skeleton tone="accent" className="mt-4 h-10 w-full"/></section><section className="dashboard-card p-5"><Skeleton className="mb-5 h-5 w-32"/><Skeleton className="mb-4 h-11 w-full"/><Skeleton className="mb-4 h-24 w-full"/><Skeleton tone="accent" className="h-10 w-full"/></section></div></div></div>}

export function AdminSupportSkeleton(){return <div role="status" aria-label="در حال بارگذاری گفت‌وگوهای موکلین"><DashboardHeaderSkeleton/><FilterBarSkeleton/><section className="dashboard-card space-y-3 p-5">{Array.from({length:7}).map((_,i)=><ListRowSkeleton key={i}/>)}</section></div>}
export function AdminSupportThreadSkeleton(){return <div role="status" aria-label="در حال بارگذاری گفت‌وگو" className="mx-auto max-w-5xl"><BackLinkSkeleton/><DashboardHeaderSkeleton action/><div className="mb-6 flex gap-3"><Skeleton className="h-10 w-24"/><Skeleton className="h-10 w-28"/></div><section className="dashboard-card my-6 space-y-4 p-5 md:p-6">{Array.from({length:6}).map((_,i)=><div key={i} className={`flex ${i%2?'justify-start':'justify-end'}`}><div className={`${i%2?'bg-muted':'bg-ink'} w-[72%] rounded-xl p-4`}><div className="mb-3 flex justify-between"><Skeleton tone={i%2?'default':'dark'} className="h-3 w-20"/><Skeleton tone={i%2?'default':'dark'} className="h-3 w-24"/></div><Skeleton tone={i%2?'default':'dark'} className="mb-2 h-3 w-full"/><Skeleton tone={i%2?'default':'dark'} className="h-3 w-4/5"/></div></div>)}</section><section className="dashboard-card p-5"><Skeleton className="mb-4 h-5 w-32"/><Skeleton className="mb-4 h-32 w-full"/><Skeleton tone="accent" className="h-10 w-28"/></section></div>}

export function AdminAppointmentsSkeleton(){return <div role="status" aria-label="در حال بارگذاری نوبت‌های مشاوره"><DashboardHeaderSkeleton/><div className="space-y-4">{Array.from({length:6}).map((_,i)=><article key={i} className="dashboard-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex-1 space-y-3"><Skeleton className="h-5 w-48"/><Skeleton className="h-3 w-40"/><Skeleton className="h-3 w-64 max-w-full"/></div><Skeleton tone="accent" className="h-6 w-24 rounded-full"/></div><div className="mt-5 flex gap-2"><Skeleton className="h-9 w-24"/><Skeleton className="h-9 w-24"/></div></article>)}</div></div>}
