import { Skeleton } from '@/components/ui/skeleton';
import { BackLinkSkeleton, DashboardHeaderSkeleton, FormFieldSkeleton, ListRowSkeleton, TextareaFieldSkeleton } from './SkeletonBlocks';

export function PortalDashboardSkeleton(){return <div role="status" aria-label="در حال بارگذاری داشبورد موکل"><DashboardHeaderSkeleton action/><div className="dashboard-card mb-6 flex items-start gap-3 border-accent/30 bg-accent/5 p-4"><Skeleton tone="accent" className="size-5 shrink-0 rounded-full"/><div className="flex-1 space-y-2"><Skeleton className="h-3 w-full"/><Skeleton className="h-3 w-4/5"/></div></div><div className="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-3">{Array.from({length:3}).map((_,i)=><div key={i} className="dashboard-stat"><div className="flex items-center justify-between"><div className="space-y-3"><Skeleton className="h-4 w-24"/><Skeleton tone="accent" className="h-9 w-14"/></div><Skeleton tone="accent" className="size-11 rounded-lg"/></div></div>)}</div><div className="grid grid-cols-1 gap-6 xl:grid-cols-2">{Array.from({length:2}).map((_,i)=><section key={i} className="dashboard-card p-5"><div className="mb-5 flex justify-between"><Skeleton className="h-5 w-32"/><Skeleton tone="accent" className="h-4 w-20"/></div><div className="space-y-3">{Array.from({length:4}).map((_,r)=><ListRowSkeleton key={r}/>)}</div></section>)}</div></div>}

export function PortalCasesSkeleton(){return <div role="status" aria-label="در حال بارگذاری پرونده‌های من"><DashboardHeaderSkeleton/><div className="grid grid-cols-1 gap-4 lg:grid-cols-2">{Array.from({length:6}).map((_,i)=><div key={i} className="dashboard-card p-5"><div className="flex items-start justify-between gap-4"><div className="flex-1"><Skeleton tone="accent" className="mb-4 h-6 w-20 rounded-full"/><Skeleton className="mb-3 h-5 w-3/4"/><Skeleton className="mb-5 h-3 w-36"/></div><Skeleton className="size-6"/></div><div className="rounded-lg bg-muted/50 p-3"><Skeleton className="mb-2 h-3 w-full"/><Skeleton className="h-3 w-28"/></div></div>)}</div></div>}

export function PortalCaseDetailSkeleton(){return <div role="status" aria-label="در حال بارگذاری جزئیات پرونده"><BackLinkSkeleton/><DashboardHeaderSkeleton action/><div className="grid grid-cols-1 items-start gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="dashboard-card p-5"><Skeleton className="mb-5 h-5 w-28"/><div className="space-y-5">{Array.from({length:5}).map((_,i)=><article key={i} className="border-r-2 border-accent/35 pr-5"><Skeleton className="mb-2 h-4 w-44"/><Skeleton className="mb-3 h-3 w-28"/><Skeleton className="mb-2 h-3 w-full"/><Skeleton className="h-3 w-4/5"/></article>)}</div></section><div className="space-y-6"><section className="dashboard-card p-5"><Skeleton className="mb-5 h-5 w-32"/>{Array.from({length:3}).map((_,i)=><div key={i} className="mb-4 space-y-2"><Skeleton className="h-3 w-24"/><Skeleton className="h-4 w-full"/></div>)}</section><section className="dashboard-card p-5"><Skeleton className="mb-5 h-5 w-36"/>{Array.from({length:3}).map((_,i)=><div key={i} className="mb-3 rounded-lg border border-border p-4"><div className="flex gap-3"><Skeleton tone="accent" className="size-8"/><div className="flex-1"><Skeleton className="mb-2 h-4 w-36"/><Skeleton className="h-3 w-full"/></div></div><Skeleton className="mt-3 h-9 w-full"/></div>)}</section></div></div></div>}

export function PortalMessagesSkeleton(){return <div role="status" aria-label="در حال بارگذاری پیام‌ها"><DashboardHeaderSkeleton/><div className="grid grid-cols-1 items-start gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="dashboard-card p-5"><Skeleton className="mb-5 h-5 w-32"/><div className="space-y-3">{Array.from({length:6}).map((_,i)=><ListRowSkeleton key={i}/>)}</div></section><section className="dashboard-card p-5 xl:sticky xl:top-24"><Skeleton className="mb-5 h-5 w-36"/><FormFieldSkeleton/><div className="mt-4"><TextareaFieldSkeleton/></div><Skeleton tone="accent" className="mt-4 h-10 w-full"/></section></div></div>}

export function PortalThreadSkeleton(){return <div role="status" aria-label="در حال بارگذاری گفت‌وگو" className="mx-auto max-w-4xl"><BackLinkSkeleton/><DashboardHeaderSkeleton action/><section className="dashboard-card mb-6 space-y-4 p-5 md:p-6">{Array.from({length:6}).map((_,i)=><div key={i} className={`flex ${i%2?'justify-start':'justify-end'}`}><div className={`${i%2?'bg-muted':'bg-sky-100'} w-[78%] rounded-xl p-4`}><div className="mb-3 flex justify-between"><Skeleton tone={i%2?'default':'dark'} className="h-3 w-20"/><Skeleton tone={i%2?'default':'dark'} className="h-3 w-24"/></div><Skeleton tone={i%2?'default':'dark'} className="mb-2 h-3 w-full"/><Skeleton tone={i%2?'default':'dark'} className="h-3 w-4/5"/></div></div>)}</section><section className="dashboard-card p-5"><Skeleton className="mb-4 h-5 w-28"/><Skeleton className="mb-4 h-28 w-full"/><Skeleton tone="accent" className="h-10 w-28"/></section></div>}

export function PortalAppointmentsSkeleton(){return <div role="status" aria-label="در حال بارگذاری نوبت مشاوره"><DashboardHeaderSkeleton/><div className="grid grid-cols-1 items-start gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="dashboard-card p-5"><Skeleton className="mb-5 h-5 w-36"/><div className="space-y-3">{Array.from({length:5}).map((_,i)=><div key={i} className="rounded-lg border border-border p-4"><div className="flex justify-between gap-4"><div className="flex-1 space-y-3"><Skeleton className="h-4 w-44"/><Skeleton className="h-3 w-40"/><Skeleton className="h-3 w-full"/></div><Skeleton tone="accent" className="h-6 w-24 rounded-full"/></div></div>)}</div></section><section className="dashboard-card p-5 xl:sticky xl:top-24"><Skeleton className="mb-5 h-5 w-36"/><div className="space-y-4"><FormFieldSkeleton/><FormFieldSkeleton/><TextareaFieldSkeleton/><Skeleton tone="accent" className="h-10 w-full"/></div></section></div></div>}

export function PortalProfileSkeleton(){return <div role="status" aria-label="در حال بارگذاری اطلاعات حساب" className="max-w-5xl"><DashboardHeaderSkeleton/><div className="grid grid-cols-1 items-start gap-6 lg:grid-cols-2"><section className="dashboard-card p-6"><Skeleton className="mb-6 h-5 w-32"/><div className="space-y-5"><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><Skeleton tone="accent" className="h-10 w-full"/></div></section><section className="dashboard-card p-6"><Skeleton className="mb-6 h-5 w-32"/><div className="space-y-5"><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><Skeleton tone="accent" className="h-10 w-full"/></div></section></div></div>}
