import { Skeleton } from '@/components/ui/skeleton';
import { PublicHeroSkeleton, SectionHeadingSkeleton, FormFieldSkeleton, TextareaFieldSkeleton } from './SkeletonBlocks';

export function HomePageSkeleton() {
  return (
    <div role="status" aria-label="در حال بارگذاری صفحه اصلی">
      <section className="bg-ink">
        <div className="mx-auto max-w-6xl px-6 pb-20 pt-16 md:pb-28 md:pt-24">
          <Skeleton tone="dark" className="mb-6 h-12 w-[42rem] max-w-full md:h-16" />
          <Skeleton tone="dark" className="mb-3 h-4 w-[38rem] max-w-full" />
          <Skeleton tone="dark" className="mb-10 h-4 w-[30rem] max-w-[85%]" />
          <div className="flex gap-4"><Skeleton tone="accent" className="h-11 w-36" /><Skeleton tone="dark" className="h-11 w-32" /></div>
        </div>
      </section>
      <section className="border-b border-border bg-card"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-6 px-6 py-8 lg:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i} className="flex items-center gap-3"><Skeleton tone="accent" className="size-8"/><Skeleton className="h-4 w-28"/></div>)}</div></section>
      <section className="bg-parchment"><div className="mx-auto max-w-6xl px-6 py-20"><SectionHeadingSkeleton/><div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="rounded-sm border border-border bg-card p-6"><Skeleton tone="accent" className="mb-5 size-12"/><Skeleton className="mb-3 h-6 w-2/3"/><Skeleton className="mb-2 h-4 w-full"/><Skeleton className="mb-5 h-4 w-4/5"/><Skeleton tone="accent" className="h-4 w-24"/></div>)}</div></div></section>
      <section className="bg-ink"><div className="mx-auto max-w-6xl px-6 py-20"><SectionHeadingSkeleton dark/><div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i}><Skeleton tone="accent" className="mb-4 size-9"/><Skeleton tone="dark" className="mb-3 h-5 w-32"/><Skeleton tone="dark" className="mb-2 h-3 w-full"/><Skeleton tone="dark" className="h-3 w-4/5"/></div>)}</div></div></section>
      <section className="bg-parchment"><div className="mx-auto max-w-6xl px-6 py-20"><Skeleton className="mb-12 h-9 w-72"/><div className="flex flex-col items-center gap-8 rounded-sm border border-border bg-card p-8 md:flex-row"><Skeleton tone="accent" className="size-40 shrink-0 rounded-full"/><div className="flex-1 space-y-4"><Skeleton className="h-6 w-48"/><Skeleton tone="accent" className="h-4 w-36"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-5/6"/><Skeleton tone="accent" className="h-10 w-32"/></div></div></div></section>
      <section className="bg-card"><div className="mx-auto max-w-6xl px-6 py-20"><SectionHeadingSkeleton/><div className="grid grid-cols-1 gap-6 md:grid-cols-3">{Array.from({length:3}).map((_,i)=><div key={i} className="rounded-sm border border-border bg-parchment p-6"><Skeleton tone="accent" className="mb-3 h-3 w-20"/><Skeleton className="mb-4 h-5 w-4/5"/><Skeleton className="mb-2 h-3 w-full"/><Skeleton className="mb-5 h-3 w-5/6"/><Skeleton className="h-3 w-28"/></div>)}</div></div></section>
      <section className="bg-teal"><div className="mx-auto max-w-4xl px-6 py-16 text-center"><Skeleton tone="dark" className="mx-auto mb-4 h-8 w-80 max-w-full"/><Skeleton tone="dark" className="mx-auto mb-8 h-4 w-[34rem] max-w-full"/><div className="flex justify-center gap-4"><Skeleton tone="accent" className="h-11 w-36"/><Skeleton tone="dark" className="h-11 w-32"/></div></div></section>
    </div>
  );
}

export function AboutPageSkeleton() {
  return <div role="status" aria-label="در حال بارگذاری درباره ما"><PublicHeroSkeleton/><section className="bg-parchment"><div className="mx-auto grid max-w-6xl grid-cols-1 gap-12 px-6 py-20 lg:grid-cols-3"><div className="space-y-5 lg:col-span-2"><Skeleton className="h-8 w-48"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-4/5"/><Skeleton className="mt-6 h-4 w-full"/><Skeleton className="h-4 w-3/4"/></div><div className="rounded-sm bg-ink p-8">{Array.from({length:3}).map((_,i)=><div key={i} className="mb-6 space-y-2"><Skeleton tone="accent" className="h-8 w-28"/><Skeleton tone="dark" className="h-3 w-36"/></div>)}</div></div></section><section className="bg-card"><div className="mx-auto max-w-6xl px-6 py-20"><SectionHeadingSkeleton/><div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i}><Skeleton tone="accent" className="mb-5 size-12"/><Skeleton className="mb-3 h-5 w-32"/><Skeleton className="mb-2 h-3 w-full"/><Skeleton className="h-3 w-4/5"/></div>)}</div></div></section><section className="bg-parchment"><div className="mx-auto max-w-6xl px-6 py-20"><SectionHeadingSkeleton/><div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i}><Skeleton tone="accent" className="mb-4 h-9 w-10"/><Skeleton className="mb-3 h-5 w-32"/><Skeleton className="mb-2 h-3 w-full"/><Skeleton className="h-3 w-4/5"/></div>)}</div></div></section></div>;
}

export function ContactPageSkeleton() {
  return <div role="status" aria-label="در حال بارگذاری تماس با ما"><PublicHeroSkeleton/><section className="bg-parchment"><div className="mx-auto grid max-w-6xl grid-cols-1 gap-12 px-6 py-16 lg:grid-cols-5"><div className="dashboard-card grid gap-5 p-6 lg:col-span-3 md:grid-cols-2"><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><FormFieldSkeleton/><TextareaFieldSkeleton rows={6}/><Skeleton tone="accent" className="h-11 w-36"/></div><div className="lg:col-span-2"><div className="rounded-sm bg-ink p-8"><Skeleton tone="accent" className="mb-6 h-6 w-40"/>{Array.from({length:5}).map((_,i)=><div key={i} className="mb-5 flex gap-3"><Skeleton tone="accent" className="size-5 shrink-0"/><div className="flex-1 space-y-2"><Skeleton tone="dark" className="h-4 w-4/5"/><Skeleton tone="dark" className="h-3 w-24"/></div></div>)}</div></div></div></section></div>;
}

export function FaqPageSkeleton() {
  return <div role="status" aria-label="در حال بارگذاری سوالات متداول"><PublicHeroSkeleton/><section className="bg-parchment"><div className="mx-auto max-w-3xl px-6 py-16"><div className="flex flex-col gap-4">{Array.from({length:7}).map((_,i)=><div key={i} className="rounded-sm border border-border bg-card px-6 py-5"><div className="flex items-center justify-between gap-4"><Skeleton className="h-5 w-3/4"/><Skeleton tone="accent" className="size-5"/></div></div>)}</div></div></section></div>;
}

export function BlogIndexSkeleton() {
  return <div role="status" aria-label="در حال بارگذاری وبلاگ"><PublicHeroSkeleton/><section className="bg-parchment"><div className="mx-auto max-w-6xl px-6 py-16"><div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">{Array.from({length:6}).map((_,i)=><article key={i} className="overflow-hidden rounded-sm border border-border bg-card"><Skeleton tone="accent" className="aspect-video w-full rounded-none"/><div className="p-6"><div className="mb-3 flex items-center justify-between"><Skeleton tone="accent" className="h-3 w-20"/><Skeleton className="h-3 w-16"/></div><Skeleton className="mb-4 h-6 w-4/5"/><Skeleton className="mb-2 h-3 w-full"/><Skeleton className="mb-5 h-3 w-5/6"/><Skeleton tone="accent" className="h-4 w-24"/></div></article>)}</div></div></section></div>;
}

export function BlogArticleSkeleton() {
  return <div role="status" aria-label="در حال بارگذاری مقاله"><section className="bg-ink"><div className="mx-auto max-w-4xl px-6 py-12"><Skeleton tone="dark" className="mb-8 h-4 w-36"/><div className="mb-3 flex gap-3"><Skeleton tone="accent" className="h-3 w-20"/><Skeleton tone="accent" className="h-3 w-12"/></div><Skeleton tone="dark" className="mb-4 h-10 w-[40rem] max-w-full"/><Skeleton tone="dark" className="h-3 w-40"/></div></section><article className="bg-parchment"><div className="mx-auto max-w-4xl px-6 py-12 md:py-16"><Skeleton tone="accent" className="mb-10 aspect-video w-full rounded-xl"/><div className="mb-10 border-r-4 border-gold pr-5"><Skeleton className="mb-3 h-5 w-full"/><Skeleton className="h-5 w-4/5"/></div><div className="space-y-4">{Array.from({length:8}).map((_,i)=><Skeleton key={i} className={`h-4 ${i%3===2?'w-4/5':'w-full'}`}/>)}</div><div className="mt-10 flex items-center justify-between gap-4 border-t border-border pt-6"><Skeleton className="h-4 w-56"/><Skeleton tone="accent" className="h-10 w-32"/></div></div></article></div>;
}

export function LawyersIndexSkeleton() {
  return <div role="status" aria-label="در حال بارگذاری معرفی وکلا"><PublicHeroSkeleton/><section className="bg-parchment"><div className="mx-auto max-w-6xl px-6 py-20"><div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i} className="flex flex-col items-center rounded-sm border border-border bg-card p-6 text-center"><Skeleton tone="accent" className="size-40 rounded-full"/><Skeleton className="mt-4 mb-2 h-5 w-32"/><Skeleton className="mb-4 h-3 w-24"/><div className="mb-4 flex gap-2"><Skeleton tone="accent" className="h-6 w-20"/><Skeleton tone="accent" className="h-6 w-16"/></div><Skeleton className="h-3 w-24"/></div>)}</div></div></section></div>;
}

export function LawyerDetailSkeleton() {
  return <div role="status" aria-label="در حال بارگذاری پروفایل وکیل"><section className="bg-ink"><div className="mx-auto max-w-6xl px-6 py-14"><Skeleton tone="dark" className="mb-10 h-4 w-40"/><div className="flex flex-col items-center gap-8 sm:flex-row sm:items-start"><Skeleton tone="accent" className="size-40 shrink-0 rounded-full"/><div className="flex-1 space-y-4"><Skeleton tone="dark" className="h-8 w-56"/><Skeleton tone="accent" className="h-4 w-32"/><Skeleton tone="dark" className="h-3 w-44"/><div className="flex gap-2"><Skeleton tone="dark" className="h-7 w-24"/><Skeleton tone="dark" className="h-7 w-20"/></div></div></div></div></section><section className="bg-parchment"><div className="mx-auto grid max-w-6xl grid-cols-1 gap-12 px-6 py-16 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2"><Skeleton className="h-6 w-40"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-5/6"/><Skeleton className="h-4 w-4/5"/></div><div className="space-y-6"><div className="rounded-sm border border-border bg-card p-6"><Skeleton className="mb-5 h-5 w-32"/>{Array.from({length:3}).map((_,i)=><Skeleton key={i} className="mb-3 h-4 w-full"/>)}</div><div className="rounded-sm bg-ink p-6"><Skeleton tone="dark" className="mx-auto mb-5 h-4 w-4/5"/><Skeleton tone="accent" className="h-10 w-full"/></div></div></div></section></div>;
}

export function PracticeAreasIndexSkeleton() {
  return <div role="status" aria-label="در حال بارگذاری حوزه‌های تخصصی"><PublicHeroSkeleton/><section className="bg-parchment"><div className="mx-auto max-w-6xl px-6 py-20"><div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="rounded-sm border border-border bg-card p-7"><Skeleton tone="accent" className="mb-5 size-12"/><Skeleton className="mb-3 h-6 w-2/3"/><Skeleton className="mb-2 h-4 w-full"/><Skeleton className="mb-6 h-4 w-5/6"/><Skeleton tone="accent" className="h-4 w-28"/></div>)}</div></div></section></div>;
}

export function PracticeAreaDetailSkeleton() {
  return <div role="status" aria-label="در حال بارگذاری حوزه تخصصی"><section className="bg-ink"><div className="mx-auto max-w-6xl px-6 py-14"><Skeleton tone="dark" className="mb-8 h-4 w-40"/><Skeleton tone="accent" className="mb-5 size-12"/><Skeleton tone="dark" className="mb-5 h-10 w-[34rem] max-w-full"/><Skeleton tone="dark" className="h-4 w-[42rem] max-w-full"/></div></section><section className="bg-parchment"><div className="mx-auto grid max-w-6xl grid-cols-1 gap-10 px-6 py-16 lg:grid-cols-[1fr_22rem]"><div className="space-y-8"><div className="space-y-4"><Skeleton className="h-7 w-48"/>{Array.from({length:5}).map((_,i)=><Skeleton key={i} className={`${i===4?'w-4/5':'w-full'} h-4`}/>)}</div><div className="space-y-4"><Skeleton className="h-6 w-40"/>{Array.from({length:4}).map((_,i)=><div key={i} className="flex gap-3"><Skeleton tone="accent" className="size-5 shrink-0"/><Skeleton className="h-4 w-4/5"/></div>)}</div></div><aside className="space-y-6"><div className="rounded-sm border border-border bg-card p-6"><Skeleton className="mb-5 h-5 w-36"/>{Array.from({length:4}).map((_,i)=><Skeleton key={i} className="mb-3 h-4 w-full"/>)}</div><div className="rounded-sm bg-ink p-6"><Skeleton tone="dark" className="mb-5 h-4 w-full"/><Skeleton tone="accent" className="h-10 w-full"/></div></aside></div></section></div>;
}

function AuthCardSkeleton({ fields, secondary = false }: { fields: number; secondary?: boolean }) {
  return <section className="bg-parchment py-14 md:py-20"><div className="mx-auto max-w-md px-6"><div className="rounded-xl border border-border bg-card p-6 shadow-sm md:p-8"><div className="mb-7 text-center"><Skeleton tone="accent" className="mx-auto mb-4 size-12 rounded-full"/><Skeleton className="mx-auto mb-3 h-7 w-44"/><Skeleton className="mx-auto h-4 w-72 max-w-full"/></div><div className="space-y-5">{Array.from({length:fields}).map((_,i)=><FormFieldSkeleton key={i}/>)}</div><Skeleton tone="accent" className="mt-6 h-11 w-full"/>{secondary && <Skeleton className="mx-auto mt-5 h-4 w-44"/>}</div></div></section>;
}
export function LoginPageSkeleton(){return <AuthCardSkeleton fields={2} secondary/>;}
export function SignupPageSkeleton(){return <AuthCardSkeleton fields={3} secondary/>;}
export function ForgotPasswordPageSkeleton(){return <AuthCardSkeleton fields={1}/>;}
